# Generated by Django 2.2.6 on 2019-11-01 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviev2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entradas', models.IntegerField(default=1)),
                ('horario', models.CharField(max_length=10)),
                ('cartelera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moviev2.Cartelera')),
            ],
        ),
    ]
