# Generated by Django 2.2.6 on 2019-11-01 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviev2', '0002_pelicula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moviev2.Cliente')),
                ('pelicula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moviev2.Pelicula')),
            ],
        ),
    ]
