# Generated by Django 2.2.6 on 2019-11-01 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviev2', '0003_detalle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartelera',
            old_name='hora',
            new_name='duracion',
        ),
    ]
