# Generated by Django 2.2.6 on 2019-11-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviev2', '0004_auto_20191101_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartelera',
            name='duracion',
            field=models.CharField(max_length=8),
        ),
    ]
