# Generated by Django 2.2.6 on 2019-11-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviev2', '0005_auto_20191101_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle',
            name='cliente',
        ),
        migrations.AddField(
            model_name='detalle',
            name='cliente',
            field=models.ManyToManyField(to='moviev2.Cliente'),
        ),
        migrations.RemoveField(
            model_name='detalle',
            name='pelicula',
        ),
        migrations.AddField(
            model_name='detalle',
            name='pelicula',
            field=models.ManyToManyField(to='moviev2.Pelicula'),
        ),
    ]
