# Generated by Django 2.2.6 on 2019-11-01 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviev2', '0006_auto_20191101_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle',
            name='cliente',
        ),
        migrations.AddField(
            model_name='detalle',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moviev2.Cliente'),
        ),
        migrations.RemoveField(
            model_name='detalle',
            name='pelicula',
        ),
        migrations.AddField(
            model_name='detalle',
            name='pelicula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moviev2.Pelicula'),
        ),
    ]
